import { beforeAll, describe, expect, it } from 'vitest';
import { STAGES } from '../src/core/lifecycle.js';
import { reportProject, XSS_NOTE, type ReportProject } from './report-fixture.js';

describe('sdlc report (model, json, markdown)', () => {
  let p: ReportProject;
  beforeAll(() => {
    p = reportProject();
  });

  it('json: summary, per-stage counts in lifecycle order, blocked and awaiting-human', () => {
    const r = p.cli(['report', '--format', 'json']);
    expect(r.code, r.stderr).toBe(0);
    const m = r.json();
    expect(m.harness).toMatchObject({ tool: 'scdl' });
    expect(m.project.name).toBeTruthy();
    expect(m.summary.active).toBe(2);
    expect(m.summary.archived).toBe(0);
    expect(m.summary.byStage.map((s: { stage: string }) => s.stage)).toEqual([...STAGES]);
    expect(m.summary.byStage.reduce((n: number, s: { count: number }) => n + s.count, 0)).toBe(2);
    expect(m.summary.blocked).toBe(1);
    expect(m.changes.map((c: { id: string }) => c.id).sort()).toEqual(['add-farewell', 'say-hello']);
    const hello = m.changes.find((c: { id: string }) => c.id === 'say-hello');
    expect(hello.gates.find((g: { id: string }) => g.id === 'intent').status).toBe('approved');
    expect(hello.next.actor).toBe('agent');
    expect(hello.movedInPeriod).toBe(true);
    const farewell = m.changes.find((c: { id: string }) => c.id === 'add-farewell');
    expect(farewell.gates.find((g: { id: string }) => g.id === 'intent').status).toBe('rejected');
    expect(m.layout).toHaveProperty('score');
    expect(m.metrics).toHaveProperty('rejections', 1);
  });

  it('json: events come from the project log, oldest first, and carry the rejection note', () => {
    const m = p.cli(['report', '--json']).json();
    const events = m.events.map((e: { event: string }) => e.event);
    expect(events).toEqual(expect.arrayContaining(['harness.initialized', 'gate.intent.approved', 'gate.intent.rejected']));
    const ts = m.events.map((e: { ts: string }) => e.ts);
    expect([...ts].sort()).toEqual(ts);
    expect(m.events.find((e: { event: string }) => e.event === 'gate.intent.rejected').detail).toContain(XSS_NOTE);
  });

  it('--since filters events and movement; negative: a future date shows no movement', () => {
    const m = p.cli(['report', '--json', '--since', '2999-01-01']).json();
    expect(m.period.since).toMatch(/^2999-01-01/);
    expect(m.events).toEqual([]);
    expect(m.changes.every((c: { movedInPeriod: boolean }) => !c.movedInPeriod)).toBe(true);
    expect(m.summary.active).toBe(2);
  });

  it('--change limits the report to one change; negative: the other change is absent', () => {
    const m = p.cli(['report', '--json', '--change', 'say-hello']).json();
    expect(m.changes.map((c: { id: string }) => c.id)).toEqual(['say-hello']);
    expect(m.events.every((e: { change?: string }) => e.change === undefined || e.change === 'say-hello')).toBe(true);
  });

  it('rejects an invalid --since and an unknown --format', () => {
    expect(p.cli(['report', '--json', '--since', 'yesterday']).code).toBe(1);
    expect(p.cli(['report', '--format', 'pdf']).code).toBe(1);
  });

  it('markdown: headline numbers, one row per change, the scdl footer', () => {
    const r = p.cli(['report', '--format', 'md']);
    expect(r.code, r.stderr).toBe(0);
    const md = r.stdout;
    expect(md).toMatch(/^# /m);
    expect(md).toMatch(/\| *say-hello *\|/);
    expect(md).toMatch(/\| *add-farewell *\|/);
    expect(md).toMatch(/blocked/i);
    expect(md).toContain('Generated by [scdl]');
  });

  it('--out writes the report to a file instead of stdout', () => {
    const r = p.cli(['report', '--format', 'md', '--out', 'reports/status.md']);
    expect(r.code, r.stderr).toBe(0);
    expect(r.stdout).not.toMatch(/\| *say-hello *\|/);
  });
});
