import type { ReportModel } from './model.js';
import { PROJECT_URL } from '../core/license.js';

function cell(value: unknown): string {
  return String(value ?? '-')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, '<br>');
}

function stages(model: ReportModel): string[] {
  return [
    '## Stages', '',
    '| Stage | Active |',
    '| --- | ---: |',
    ...model.summary.byStage.map((stage) => `| ${cell(stage.title)} | ${stage.count} |`),
    '',
  ];
}

function changes(model: ReportModel): string[] {
  return [
    '## Changes', '',
    '| Change | Stage | Tasks | Verification | Next |',
    '| --- | --- | --- | --- | --- |',
    ...model.changes.map((change) =>
      `| ${cell(change.id)} | ${cell(change.stageTitle)} | ${change.tasks.complete}/${change.tasks.total} | ${cell(change.verification)} | ${cell(change.next.message)} |`),
    '',
  ];
}

function leadTimes(model: ReportModel): string[] {
  const m = model.metrics.medianLeadTimeHours;
  return [
    '## Median lead times (hours)', '',
    `Intent to spec: ${cell(m.intentToSpecApproval)} · Spec to plan: ${cell(m.specToPlanApproval)} · Plan to verified: ${cell(m.planToVerified)} · Verified to review: ${cell(m.verifiedToReviewApproval)} · Created to archived: ${cell(m.createdToArchived)}`,
    '',
  ];
}

function events(model: ReportModel): string[] {
  return [
    '## Recent events', '',
    ...model.events.map((event) =>
      `- ${event.ts} ${event.change ? `${cell(event.change)}: ` : ''}${cell(event.event)}${event.detail ? ` — ${cell(event.detail)}` : ''}`),
    '',
  ];
}

function layout(model: ReportModel): string[] {
  const missing = model.layout.missingRequired.length
    ? ` Missing required: ${model.layout.missingRequired.join(', ')}.`
    : '';
  return [
    '## Layout readiness', '',
    `${model.layout.ready ? 'Ready' : 'Incomplete'} (${model.layout.score}%).${missing}`,
    '',
  ];
}

function footer(model: ReportModel): string {
  return `<sub>Generated by [scdl](${PROJECT_URL}) ${model.harness.version} · license: ${model.harness.license}</sub>`;
}

export function renderReportMarkdown(model: ReportModel): string {
  const lines = [
    `# ${cell(model.project.name)} SDLC progress (${model.period.since ?? 'all time'} to ${model.period.until})`,
    '',
    `${model.summary.active} active · ${model.summary.archived} archived · ${model.summary.blocked} blocked · ${model.summary.awaitingHuman} awaiting a person`,
    '',
    ...stages(model),
    ...changes(model),
    ...leadTimes(model),
    ...events(model),
    ...layout(model),
    footer(model),
  ];
  return lines.join('\n');
}
