import * as path from 'node:path';
import { normalizeNewlines, readText } from '../core/fs-utils.js';
import {
  generatedNotice,
  harnessStamp,
  LEGAL_FILES,
  LICENSE_REFERENCE,
  LICENSE_SUMMARY,
  LICENSOR,
  LICENSOR_URL,
  PROJECT_URL,
  REQUIRED_NOTICE,
} from '../core/license.js';
import { harnessPackageDir } from '../core/openspec-schema.js';
import { harnessVersion } from '../core/version.js';
import { AGENT_IDS, loadAgent, loadWorkflow, WORKFLOW_IDS } from './assets.js';
import { appendNotice, renderBody, yamlString } from './render.js';
import { harnessHooks } from './settings.js';
import { allowedToolsFor } from './skills.js';

/**
 * A Claude Code plugin with the same workflows, subagents and hooks as a
 * project install, for organization-wide distribution through a (private)
 * plugin marketplace - the playbook's recommended channel for skills and
 * hooks. Plugin skills are namespaced by the plugin, so they are invoked as
 * `/sdlc:<id>`, the same form the project-level commands use.
 */
export interface PluginFile {
  path: string;
  content: string;
}

export const PLUGIN_NAME = 'sdlc';

export function renderClaudePlugin(cli = 'sdlc'): PluginFile[] {
  const version = harnessVersion();
  // The plugin is distributed by the licensor itself, so its notices name the
  // license terms but not a project's choice between them.
  const notice = generatedNotice(harnessStamp({ license: { type: 'community' } }, version), 'markdown', false);
  const files: PluginFile[] = [];
  files.push({
    path: '.claude-plugin/plugin.json',
    content: `${JSON.stringify({
      name: PLUGIN_NAME,
      version,
      description: 'AI-native SDLC workflows (intent, spec, plan, build, verify, review, release, archive, triage) with gates, built on OpenSpec. Requires the `sdlc` CLI (npm package scdl).',
      author: { name: LICENSOR, url: LICENSOR_URL },
      homepage: PROJECT_URL,
      repository: PROJECT_URL,
      license: LICENSE_REFERENCE,
      keywords: ['sdlc', 'openspec', 'spec-driven', 'gates', 'governance'],
    }, null, 2)}\n`,
  });
  for (const id of WORKFLOW_IDS) {
    const wf = loadWorkflow(id);
    files.push({
      path: `skills/${id}/SKILL.md`,
      content: appendNotice([
        '---',
        `name: ${id}`,
        `description: ${yamlString(wf.description)}`,
        ...(wf.whenToUse ? [`when_to_use: ${yamlString(wf.whenToUse)}`] : []),
        ...(wf.argumentHint ? [`argument-hint: ${yamlString(wf.argumentHint)}`] : []),
        `license: ${yamlString(LICENSE_SUMMARY)}`,
        `compatibility: ${yamlString(`Requires the sdlc CLI (${cli}) from the scdl package.`)}`,
        `allowed-tools: ${allowedToolsFor(cli)}`,
        'metadata:',
        `  author: ${yamlString(LICENSOR)}`,
        '  version: "1"',
        `  generatedBy: "scdl ${version}"`,
        '---',
        '',
        renderBody(wf.body, { surface: 'plugin-skill', cli }),
      ].join('\n'), notice),
    });
  }
  for (const id of AGENT_IDS) {
    const agent = loadAgent(id);
    const tools = agent.tools.map((t) => ({ read: 'Read', grep: 'Grep', glob: 'Glob', bash: 'Bash', edit: 'Edit', write: 'Write' }[t] ?? t)).join(', ');
    files.push({
      path: `agents/${agent.name}.md`,
      content: appendNotice([
        '---',
        `name: ${agent.name}`,
        `description: ${yamlString(agent.description)}`,
        `tools: ${tools}`,
        '---',
        '',
        renderBody(agent.body, { surface: 'claude-agent', cli }),
      ].join('\n'), notice),
    });
  }
  files.push({ path: 'hooks/hooks.json', content: `${JSON.stringify({ hooks: harnessHooks(cli) }, null, 2)}\n` });
  files.push({
    path: 'README.md',
    content: [
      '# sdlc - Claude Code plugin',
      '',
      'Generated by `sdlc plugin build` from the templates in this repository; do not edit by hand.',
      '',
      'Install the CLI once per machine, add the marketplace, install the plugin, then set up each project:',
      '',
      '```bash',
      'npm install -g github:marin-ai-tech/scdl   # provides the `sdlc` CLI (and OpenSpec)',
      '```',
      '',
      '```text',
      '/plugin marketplace add marin-ai-tech/scdl',
      '/plugin install sdlc@scdl',
      '```',
      '',
      '```bash',
      'sdlc init --tools none        # OpenSpec root, sdlc schema, openspec/sdlc.yaml (Claude files come from the plugin)',
      'sdlc init --tools opencode    # ...or also set up OpenCode in the same project',
      '```',
      '',
      'Workflows: ' + WORKFLOW_IDS.map((id) => `\`/sdlc:${id}\``).join(', ') + '.',
      '',
      '## License',
      '',
      'scdl, including this plugin, is dual-licensed: free under the Community License (PolyForm Noncommercial 1.0.0 with',
      'the scdl Additional Permissions) for noncommercial use, open source projects and a 30-day evaluation; every other',
      'use needs a commercial license. See [LICENSE](LICENSE) and [COMMERCIAL-LICENSE.md](COMMERCIAL-LICENSE.md).',
      '',
      REQUIRED_NOTICE,
      '',
    ].join('\n'),
  });
  // Every copy of the plugin carries the license terms and the Required Notice.
  for (const rel of LEGAL_FILES) {
    const content = readText(path.join(harnessPackageDir(), rel));
    if (content !== undefined) files.push({ path: rel, content: normalizeNewlines(content) });
  }
  return files;
}

export function renderMarketplace(): string {
  return `${JSON.stringify({
    name: 'scdl',
    owner: { name: LICENSOR, url: LICENSOR_URL },
    description: 'AI-native SDLC harness for Claude Code, built on OpenSpec',
    plugins: [
      {
        name: PLUGIN_NAME,
        source: './plugin',
        description: 'AI-native SDLC workflows with human gates, verification evidence and review, built on OpenSpec',
        version: harnessVersion(),
        category: 'development',
        tags: ['sdlc', 'openspec', 'spec-driven', 'governance'],
      },
    ],
  }, null, 2)}\n`;
}
